//
//  PilatesAdviceModel.swift
//  PEMMApp2
//
//  Created by Maria Bruno on 28/10/23.
//

import Foundation
class PilatesAdviceModel {
    var pilatesadvices = [
    PilatesAdvice(name: "Pelvic Curl", description: "1. Start by laying on your back, with knees bent. Knees and heels are about sit- bone distance apart. Arms are long, and pressing into the mat beside your hips. 2. Inhale pause, then exhale: Engage your low abdominals, drawing your pelvis underneath you. The goal is to tuck your pelvis without the use of your glutes. You want your low back to feel light as a feather when it touches the mat. 3. Begin to engage your glutes, and articulate through the spine, the hips moving upward until your body is in a straight line between knees and shoulder blades. 4. Inhale pause, breathing through your ribs. Find stability through your center and down into arms and legs. 5. Exhale, and begin to drop your sternum — melting into the mat one vertebrae at a time. If you notice your lumbar (low back) is tight, or have a hard time articulating, tap into your low abdominal curl and release the glutes as your approach the mat.", imageName:"Pelvic curl image", place: "Home"),
    PilatesAdvice(name: "Chest Lift", description: "1. Lying on your back, knees bent, legs together. Interlace your fingers and place them behind your head. Press your head lighting into your hands, and find your elbows in your peripheral view. Bring energy to the inner thighs. 2. Inhale to prepare, and exhale to lift the head, neck and chest. Eyes looking toward your thighs. Try to curl up just until you feel the tip of your shoulder blades leave the mat. 3. Inhale to pause, breathing through the ribs; Exhale to lower back to the mat..", imageName:"Chest lift image",place: "Home"),
    PilatesAdvice(name: "Chest Lift with Rotation", description: "1. Inhale prepare and exhale to bring yourself into your Chest Lift Position. Inhale hold, breathing through the ribs. 2. Exhale and rotate to the right. Thinking of lifting your left rib up and across to your right hip. Focus your eyes on the outside of the knee. 3. Inhale back to center, and repeat lifting up and across to the left side. 4. Move your head, shoulders, and chest as one unit. Think of making an arc with your midsection, rather than a side bend. Do your best to keep your pelvis stable.", imageName:"Chest Lift with Rotation image", place: "Home"),
    PilatesAdvice(name: "Spine Twist Supine", description: "1. Lying on your back, arms in a T position, palms facing up; Bring your legs one at a time into tabletop — knees stacked over your hip joint, shins parallel to the floor, toes softly pointed. 2. Inhale, allowing your knees to go to the right. Exhale, draw your abdominals in, and return to center. Repeat on the left side. 3. As you rotate to one side, keep the opposite shoulder blade anchored to the mat. You want the lower half of your body to feel like a slow and controlled metronome. Slowly tick-tock back and forth with control through your mid-section.", imageName:"Spine twist supine image", place: "Home"),
    PilatesAdvice(name: "Single Leg Stretch", description: "1. Lying on your back, bring yourself into a chest lift position. One at a time bring your legs into table top (knees over hips, shins parallel to the floor). Hands on top your knees. 2. Exhale: Place both of your hands on your right knee, straighten and reach your left leg away. 3. Quickly inhale to switch the legs, and exhale as you draw your left leg into table top, and right leg extends and reaches away. 4. Continue to transfer your hands to the bent knee each time. Pull in one leg, as the other reaches. Try to minimize any movement in your trunk. Repeat 8-10 times., place: ",imageName:"Single leg strech image", place: "Home")
    
    ]
}
